# Generated by Django 4.2.4 on 2023-08-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='currentBid',
            new_name='current_bid',
        ),
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='startingBid',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bidAmount',
            new_name='bid_amount',
        ),
    ]
