# Generated by Django 4.2.4 on 2023-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_bids_bid_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(default='Images/No_Image_Available.jpg', upload_to='auctions/'),
        ),
    ]
