# Generated by Django 4.2.4 on 2023-08-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(default='static/auctions/Images/No_Image_Available.jpg', upload_to='auctions/'),
        ),
    ]
